language: elixir
elixir:
  - 1.11.2
otp_release:
  - 22.3.3

addons:
  postgres: "9.4"

env:
  global:
    - PGUSER=jhoni
    - PGPORT=5432

services:
  - postgresql

# before_script:
#   - psql -c "CREATE USER jhoni WITH PASSWORD 'jhoni';" -U postgres

script:
  - mix format --check-formatted --dry-run
  - mix credo --strict
  - mix sobelow --config
  - mix coveralls.json
