language: elixir
elixir:
  - 1.11.2
otp_release:
  - 22.3.3

addons:
  postgres: "9.4"

# env:
#   global:
#     - POSTGRES_USER=jhoni

services:
  - postgresql

# before_script:
#   - psql -c 'create database blog_test;' -U postgres

before_script:
  - psql -c "CREATE USER jhoni WITH PASSWORD 'jhoni';" -U postgres

script:
  - mix format --check-formatted --dry-run
  - mix credo --strict
  - mix sobelow --config
  - mix coveralls.json
